# Generated by Django 4.2.6 on 2024-01-08 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='average_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Общее количество часов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Характеристика урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Количество уроков'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module', to='program.module', verbose_name='Номер модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='program.course', verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Характеристика модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255, verbose_name='номер модуля'),
        ),
    ]
