# Generated by Django 4.2.6 on 2024-01-08 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_alter_course_slug_alter_module_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='average_time',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Общее количество часов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='average_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Общее количество часов'),
        ),
    ]
