# Generated by Django 4.2.6 on 2024-01-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_module_average_time_alter_course_average_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.module', verbose_name='Номер модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.course', verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристика модуля'),
        ),
    ]
