# Generated by Django 4.2.6 on 2024-01-08 17:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_lesson_module_alter_module_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='average_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Общее количество часов'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module', to='program.module', verbose_name='Номер модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='average_time',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Общее количество часов'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Характеристика модуля'),
        ),
    ]
